#!/bin/sh

#Make multilib symlinks

mount_point=$1

cur_dir=`pwd`

if [ "x$mount_point" == "x" ]
    then
    echo "Usage: $0 <mount point>"
    exit 1
fi

mv ${mount_point}/lib ${mount_point}/lib32
mkdir ${mount_point}/lib64
cd ${mount_point}
ln -s lib64 lib
echo "/lib32" >> ${mount_point}/etc/ld.so.conf

mv ${mount_point}/usr/lib ${mount_point}/usr/lib32
mkdir ${mount_point}/usr/lib64
cd ${mount_point}/usr
ln -s lib64 lib
echo "/usr/lib32" >> ${mount_point}/etc/ld.so.conf

if [ -d "${mount_point}/usr/games" ]
    then
    cd ${mount_point}/usr/games
    mv lib lib32
    mkdir lib64
    ln -s lib64 lib
    echo "/usr/games/lib32" >> ${mount_point}/etc/ld.so.conf
fi


if [ -d "${mount_point}/usr/qt/3" ]
    then
    cd ${mount_point}/usr/qt/3
    mv lib lib32
    mkdir lib64
    ln -s lib64 lib
    echo "/usr/qt/3/lib32" >> ${mount_point}/etc/ld.so.conf
fi

if [ -d "${mount_point}/usr/kde" ]
    then
    cd ${mount_point}/usr/kde
    for i in *
    do
	cd ${mount_point}/usr/kde/$i
	mv lib lib32
	mkdir lib64
	ln -s lib64 lib
	echo "/usr/kde/$i/lib32" >> ${mount_point}/etc/ld.so.conf
    done
fi

chroot ${mount_point} /sbin/ldconfig

find ${mount_point}/var/db/pkg -name CONTENTS -exec sed -i -e "s|/lib$|/lib32|g" {} \;
find ${mount_point}/var/db/pkg -name CONTENTS -exec sed -i -e "s|/lib/|/lib32/|g" {} \;

cd ${cur_dir}
