#!/sbin/runscript
# Copyright 1999-2008 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: $

service_name="btnx"
service="/usr/sbin/btnx" 

start () 
{
	ebegin "Starting ${service_name}"
	start-stop-daemon --start --quiet --exec ${service} -- -b ${flags}
	result=$?
	eend $result
}

stop () 
{
	ebegin "Stopping ${service_name}"
	start-stop-daemon --stop --quiet --exec ${service}
	result=$?
	eend $result
}

