#!/bin/sh


grep -v x86_64-pc-linux-gnu `ls /var/db/pkg/*/*/CBUILD` | awk -F: '{print $1}' | sed -e "s:/var/db/pkg/\(.*\)-[0-9].*/CBUILD:\1:g" | xargs emerge -vkb --keep-going
grep -v x86_64-pc-linux-gnu `ls /var/db/pkg/*/*/CBUILD` | awk -F: '{print $1}' | sed -e "s:/var/db/pkg/\(.*\)/CBUILD:=\1:g" | xargs emerge -vkb --keep-going


