#!/sbin/runscript
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: $

service=/usr/bin/rsync
servicename=rsyncd
pid_file=/var/run/rsyncd.pid

depend () 
{
	use net
}

start () 
{
	ebegin "Starting $servicename"
	${service} --daemon --config=/etc/systemimager/rsyncd.conf
	eend $?
}

stop () 
{
	ebegin "Stopping $servicename"
	start-stop-daemon --stop --quiet --pidfile $pid_file
	eend $?
}
