#!/bin/bash

MYTIME="+7"

cd /var/db/pkg

for i in x11-libs x11-proto dev-cpp dev-qt media-libs sys-* dev-* *
do
    echo "$i"
    if [[ `find $i -type d -mtime $MYTIME | wc -l` != 0 ]]
    then
	find "$i" -type d -mtime $MYTIME | xargs qlist -ISC | xargs emerge -v --keep-going
    fi
done



