#!/bin/bash

MYTIME="+7"

cd /var/db/pkg

for i in sys-* dev-* *
do
    echo "$i"
    id [[ `find sys-apps -type d -mtime $MYTIME | wc -l` > 0 ]]
    then
	find "$i" -type d -mtime $MYTIME | xargs qlist -ISC | xargs emerge -v --keep-going
    fi
done



