#!/bin/bash

#emerge -uv feh dex xdg-utils screenfetch scrot xcompmgr wmname \
#    alsa-utils pavucontrol xorg-xbacklight xf86-input-synaptics cheese workrave \
#    xscreensaver networkmanager network-manager-applet mate-power-manager arandr xfce4-appfinder xfce4-screenshooter gnome-control-center lxtask \
#    pcmanfm gvfs udisks udiskie lxsession lxappearance xarchiver \
#    sakura terminator conky gksu launchy \
#    gvim emacs firefox chromium putty remmina synergy \
#    fcitx-im fcitx-googlepinyin fcitx-configtool

emerge -uv feh dex xdg-utils screenfetch scrot xcompmgr wmname