#!/bin/sh
#
# Startup script to run the PCX Firewalls generated scripts.
#
# chkconfig: 2345 11 92
#
# description: Automates a packet filtering firewall with iptables.
#
# by bero@redhat.com, based on the ipchains script:
# Script Author:	Joshua Jensen <joshua@redhat.com>
#   -- hacked up by gafton with help from notting
# modified by Anton Altaparmakov <aia21@cam.ac.uk>:
# modified by Nils Philippsen <nils@redhat.de>
# modified by James Pattie <james@pcxperience.com> to support the PCX Firewall
#

# Source 'em up
. /etc/init.d/functions

LOCATION="/etc/pcx_firewall"

echo -n "Checking for necessary scripts:"

# make sure we have the necessary scripts
if [ ! -e $LOCATION/firewall ]; then
  failure $"Check for firewall:"
  echo
  exit 1
fi

success $"Check for scripts in ${LOCATION}:"
echo

start() {
  $LOCATION/firewall start && \
	    success $"Starting" || \
	    failure $"Starting"
  if [ $? -eq 0 ]; then
    touch /var/lock/subsys/iptables
  fi
  echo
}

stop() {
  $LOCATION/firewall stop && \
	    success $"Stopping" || \
	    failure $"Stopping"
  rm -f /var/lock/subsys/iptables
  echo
}

# Check for the new Mangle tables
found=`iptables -L INPUT -n -t mangle 2>&1 | /bin/grep "iptables: Table does not exist"`
if [ -z "$found" ]; then
  MANGLE_INPUT=1
else
  MANGLE_INPUT=0
fi

found=`iptables -L FORWARD -n -t mangle 2>&1 | /bin/grep "iptables: Table does not exist"`
if [ -z "$found" ]; then
  MANGLE_FORWARD=1
else
  MANGLE_FORWARD=0
fi

found=`iptables -L POSTROUTING -n -t mangle 2>&1 | /bin/grep "iptables: Table does not exist"`
if [ -z "$found" ]; then
  MANGLE_POSTROUTING=1
else
  MANGLE_POSTROUTING=0
fi

case "$1" in
  start)
	start
	;;

  stop)
	stop
	;;

  restart)
  stop
	start
	;;

  condrestart)
	[ -e /var/lock/subsys/iptables ] && restart
	;;

  status)
	echo $"Table: filter"
	iptables -L -v -n
	echo $"Table: nat"
	iptables -t nat -L -v -n
	echo $"Table: mangle"
	iptables -t mangle -L -v -n
	;;

  panic)
	echo -n $"Changing target policies to DROP: "
	iptables -P INPUT DROP && \
	    iptables -P FORWARD DROP && \
	    iptables -P OUTPUT DROP && \
	    iptables -t nat -P PREROUTING DROP && \
	    iptables -t nat -P POSTROUTING DROP && \
	    iptables -t nat -P OUTPUT DROP && \
	    iptables -t mangle -P PREROUTING DROP && \
	    iptables -t mangle -P OUTPUT DROP && \
      (if [ $MANGLE_INPUT = 1 ]; then iptables -t mangle -P INPUT DROP; fi) && \
      (if [ $MANGLE_FORWARD = 1 ]; then iptables -t mangle -P FORWARD DROP; fi) && \
      (if [ $MANGLE_POSTROUTING = 1 ]; then iptables -t mangle -P POSTROUTING DROP; fi) && \
	    success $"Changing target policies to DROP" || \
	    failure $"Changing target policies to DROP"
	    echo
        iptables -F && \
                iptables -t nat -F && \
                iptables -t mangle -F && \
                success $"Flushing all chains:" || \
                failure $"Flushing all chains:"
        iptables -X && \
                iptables -t nat -X && \
                iptables -t mangle -X && \
                success $"Removing user defined chains:" || \
                failure $"Removing user defined chains:"
        ;;

  clear)
	echo -n $"Changing target policies to ACCEPT: "
	iptables -P INPUT ACCEPT && \
	    iptables -P FORWARD ACCEPT && \
	    iptables -P OUTPUT ACCEPT && \
	    iptables -t nat -P PREROUTING ACCEPT && \
	    iptables -t nat -P POSTROUTING ACCEPT && \
	    iptables -t nat -P OUTPUT ACCEPT && \
	    iptables -t mangle -P PREROUTING ACCEPT && \
	    iptables -t mangle -P OUTPUT ACCEPT && \
      (if [ $MANGLE_INPUT = 1 ]; then iptables -t mangle -P INPUT ACCEPT; fi) && \
      (if [ $MANGLE_FORWARD = 1 ]; then iptables -t mangle -P FORWARD ACCEPT; fi) && \
      (if [ $MANGLE_POSTROUTING = 1 ]; then iptables -t mangle -P POSTROUTING ACCEPT; fi) && \
	    success $"Changing target policies to ACCEPT" || \
	    failure $"Changing target policies to ACCEPT"
	    echo
        iptables -F && \
                iptables -t nat -F && \
                iptables -t mangle -F && \
                success $"Flushing all chains:" || \
                failure $"Flushing all chains:"
        iptables -X && \
                iptables -t nat -X && \
                iptables -t mangle -X && \
                success $"Removing user defined chains:" || \
                failure $"Removing user defined chains:"
        ;;

  save)
    echo -n "save no longer supported!"
    failure $"save command:"
	;;

  *)
	echo $"Usage: $0 {start|stop|restart|condrestart|status|panic|clear}"
	exit 1
esac

exit 0

