--- makefile	2008-03-15 10:37:30.000000000 +0200
+++ makefile.fixed	2008-03-15 10:37:12.000000000 +0200
@@ -1,4 +1,3 @@
-WXCONFIG = /home/compile/wxWidgets-2.8.3/wx-config
 CPP = `$(WXCONFIG) --cxx`
 CXXFLAGS= `$(WXCONFIG) --cxxflags` -c -Os
 LDFLAGS = `$(WXCONFIG) --libs`
@@ -17,9 +16,12 @@
 .cpp.o:
 	$(CPP) $(CXXFLAGS) $< -o $@
 install:
-	cp DivFix++ /usr/local/bin
-	cp locale/tr/DivFix++.mo /usr/local/share/locale/tr/LC_MESSAGES/DivFix++.mo
-	cp locale/tr/DivFix++.mo /usr/local/share/locale/hu/LC_MESSAGES/DivFix++.mo
+	mkdir -p $(DESTDIR)/usr/bin
+	mkdir -p $(DESTDIR)/usr/share/locale/tr/LC_MESSAGES
+	mkdir -p $(DESTDIR)/usr/share/locale/hu/LC_MESSAGES
+	cp DivFix++ $(DESTDIR)/usr/bin
+	cp locale/tr/DivFix++.mo $(DESTDIR)/usr/share/locale/tr/LC_MESSAGES/DivFix++.mo
+	cp locale/tr/DivFix++.mo $(DESTDIR)/usr/share/locale/hu/LC_MESSAGES/DivFix++.mo
 uninstall:
 	rm /usr/local/bin/DivFix++
 	rm /usr/local/share/locale/tr/LC_MESSAGES/DivFix++.mo
