#!/bin/bash

die() {
	echo "#####"
	echo $1
	echo "#####"
	exit 1
}

if [ $1 = "install" ]; then
	sed -e "s|example.com/moodle|${VHOST_HOSTNAME}/${VHOST_APPDIR}|
		s|/home/example/public_html/moodle|${MY_INSTALLDIR}|
		s|/home/example/moodledata|${VHOST_ROOT}/${PN}-${PVR}|" -i ${MY_INSTALLDIR}/config-dist.php

elif [ $1 = "clean" ]; then
	echo $1
fi
