# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.13

EAPI="3"

CABAL_FEATURES="lib profile haddock hscolour"
inherit haskell-cabal

DESCRIPTION="library for directory handling"
HOMEPAGE="http://hackage.haskell.org/package/directory"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-lang/ghc-6.12.1
	dev-haskell/filepath
	dev-haskell/unix"
#	dev-haskell/old-time
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"
