# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.0

EAPI=8

CRATES="
	aho-corasick@1.1.3
	anstream@0.6.21
	anstyle-parse@0.2.7
	anstyle-query@1.1.4
	anstyle-wincon@3.0.10
	anstyle@1.0.13
	autocfg@1.5.0
	bitflags@2.9.4
	bstr@1.12.0
	bumpalo@3.19.0
	cfg-if@1.0.3
	clap@4.5.48
	clap_builder@4.5.48
	clap_complete@4.5.58
	clap_lex@0.7.5
	clap_mangen@0.2.29
	colorchoice@1.0.4
	colored@2.2.0
	crossbeam-deque@0.8.6
	crossbeam-epoch@0.9.18
	crossbeam-utils@0.8.21
	dirs-sys@0.4.1
	dirs@5.0.1
	env_filter@0.1.3
	env_logger@0.11.8
	equivalent@1.0.2
	getrandom@0.2.16
	globset@0.4.16
	hashbrown@0.16.0
	ignore@0.4.23
	indexmap@2.11.4
	is_terminal_polyfill@1.70.1
	jiff-static@0.2.15
	jiff@0.2.15
	js-sys@0.3.77
	lazy_static@1.5.0
	libc@0.2.176
	libredox@0.1.10
	log@0.4.28
	memchr@2.7.6
	merge@0.2.0
	merge_derive@0.2.0
	num-traits@0.2.19
	once_cell@1.21.3
	once_cell_polyfill@1.70.1
	option-ext@0.2.0
	portable-atomic-util@0.2.4
	portable-atomic@1.11.1
	proc-macro-error-attr2@2.0.0
	proc-macro-error2@2.0.1
	proc-macro2@1.0.101
	quote@1.0.41
	redox_users@0.4.6
	regex-automata@0.4.11
	regex-syntax@0.8.6
	regex@1.11.3
	roff@0.2.2
	rustversion@1.0.22
	same-file@1.0.6
	serde@1.0.228
	serde_core@1.0.228
	serde_derive@1.0.228
	serde_spanned@0.6.9
	similar@2.7.0
	strsim@0.11.1
	syn@2.0.106
	thiserror-impl@1.0.69
	thiserror@1.0.69
	toml@0.8.23
	toml_datetime@0.6.11
	toml_edit@0.22.27
	toml_write@0.1.2
	unicode-ident@1.0.19
	utf8parse@0.2.2
	walkdir@2.5.0
	wasi@0.11.1+wasi-snapshot-preview1
	wasm-bindgen-backend@0.2.100
	wasm-bindgen-macro-support@0.2.100
	wasm-bindgen-macro@0.2.100
	wasm-bindgen-shared@0.2.100
	wasm-bindgen@0.2.100
	web-time@1.1.0
	winapi-util@0.1.11
	windows-link@0.2.0
	windows-sys@0.48.0
	windows-sys@0.59.0
	windows-sys@0.60.2
	windows-sys@0.61.1
	windows-targets@0.48.5
	windows-targets@0.52.6
	windows-targets@0.53.4
	windows_aarch64_gnullvm@0.48.5
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_gnullvm@0.53.0
	windows_aarch64_msvc@0.48.5
	windows_aarch64_msvc@0.52.6
	windows_aarch64_msvc@0.53.0
	windows_i686_gnu@0.48.5
	windows_i686_gnu@0.52.6
	windows_i686_gnu@0.53.0
	windows_i686_gnullvm@0.52.6
	windows_i686_gnullvm@0.53.0
	windows_i686_msvc@0.48.5
	windows_i686_msvc@0.52.6
	windows_i686_msvc@0.53.0
	windows_x86_64_gnu@0.48.5
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnu@0.53.0
	windows_x86_64_gnullvm@0.48.5
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_gnullvm@0.53.0
	windows_x86_64_msvc@0.48.5
	windows_x86_64_msvc@0.52.6
	windows_x86_64_msvc@0.53.0
	winnow@0.7.13
"

inherit cargo

DESCRIPTION="LaTeX formatter written in Rust"
HOMEPAGE=""
SRC_URI="
	${CARGO_CRATE_URIS}
	https://github.com/WGUNDERWOOD/tex-fmt/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="Apache-2.0 MIT MPL-2.0 Unicode-3.0"
SLOT="0"
KEYWORDS="amd64"
