#!/sbin/runscript
# Copyright 1999-2007 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	need net dirsrv
	use krb5kdc
}

start() {
	ebegin "Starting freeIPA kpasswd"
	eval start-stop-daemon --start --quiet --exec /usr/sbin/ipa_kpasswd
	eend $?
}

stop() {
	ebegin "Stopping freeIPA kwasswd"
	start-stop-daemon --stop --quiet --name /usr/sbin/ipa_kpasswd
	eend $?
}
