#!/sbin/runscript
# Copyright 1999-2007 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	need net dirsrv-admin
	use apache
}

start() {
	ebegin "Starting freeIPA webgui"
	eval start-stop-daemon --start --quiet --exec /usr/sbin/ipa_webgui
	eend $?
}

stop() {
	ebegin "Stopping freeIPA webgui"
	start-stop-daemon --stop --quiet --name /usr/sbin/ipa_webgui
	eend $?
}
