#!/sbin/runscript
# Copyright 1999-2007 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2


start() {
	ebegin "Starting ${SVCNAME}"

	start-stop-daemon --quiet --start --pidfile /var/run/drwebd.pid --exec /opt/drweb/drwebd

	eend $? "Check your logs to see why startup failed"
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --quiet --stop --pidfile /var/run/drwebd.pid
	eend $?
}

